trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  NODE_VERSION: '20.x'
  OUTPUT_LOCATION: 'dist/spa'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(NODE_VERSION)'
  displayName: 'Use Node $(NODE_VERSION)'

- script: |
    npm ci
    npx quasar build
  displayName: 'Install & Build (Quasar)'

# Deploy usando SWA CLI (não precisa instalar task do marketplace)
- script: |
    npx -y @azure/static-web-apps-cli@1.2.5 deploy $(OUTPUT_LOCATION) \
      --deployment-token $(SWA_DEPLOYMENT_TOKEN) \
      --env production
  displayName: 'Deploy to Azure Static Web Apps (SWA CLI)'
